language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: false
before_install:
  - julia -e 'using Pkg; Pkg.add("Distributions")'
  - julia -e 'using Pkg; Pkg.add("CSVFiles")'
  - julia -e 'using Pkg; Pkg.add("DataFrames")'
  - julia -e 'using Pkg; Pkg.add("StatsBase")'
  - julia -e 'using Pkg; Pkg.add("Mimi")'
  - julia -e 'using Pkg; registry add https://github.com/mimiframework/MimiRegistry.git'
  - julia -e 'using Pkg; Pkg.add("MimiPAGE2009")'
script:
  - julia test/runtests.jl
